### ISSUE TITLE
404 and KeyError

### ISSUE THREAD

**Issue by Karel4** [parsingphase/batbox#11]
Files  imported successfully, in calendar are visible links, "search" will display map with correct recordings locations.
But all links to view something will give error 404 at browser and similar messages at console:
[25/Aug/2020 13:22:03] "GET / HTTP/1.0" 200 10354
Internal Server Error: /byday/2020-08-24
Traceback (most recent call last):
  File "/home/karel/batbox/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/karel/batbox/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/karel/batbox/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/karel/batbox/tracemap/views.py", line 124, in day
    return display_recordings_list(files, request, context)
  File "/home/karel/batbox/tracemap/views.py", line 352, in display_recordings_list
    files_with_spectrogram = [x for x in traces if x['spectrogram_url']]
  File "/home/karel/batbox/tracemap/views.py", line 352, in <listcomp>
    files_with_spectrogram = [x for x in traces if x['spectrogram_url']]
KeyError: 'spectrogram_url'
[25/Aug/2020 13:22:15] "GET /byday/2020-08-24 HTTP/1.0" 500 100050

**Comment by parsingphase** [comment]
Hi @Karel4, please let me know if this is still and issue and if so, what parameters you used with the file import script.

**Comment by parsingphase** [comment]
Closing: no reply received…
